services:
  api:
    build: .
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  ui:
    build: .
    command: streamlit run app/ui.py --server.port 8051 --server.address 0.0.0.0
    ports:
      - "8051:8051"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
